services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    hostname: prometheus

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    hostname: exporter

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
      - loki
    ports:
      - 3000:3000
    container_name: grafana
    hostname: grafana
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yaml
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml


  promtail:
    image: grafana/promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Ключевое изменение!
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/log/:/var/log/:ro
    depends_on:
      - loki
    container_name: promtail
    ports:
      - 9080:9080