services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    hostname: exporter

  promtail:
    image: grafana/promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/log/:/var/log/:ro
    container_name: promtail
    ports:
      - 9080:9080