name: mobile_app
description: "FishMasters Mobile Application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  font_awesome_flutter: ^10.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  dart_code_metrics: ^4.19.2



flutter:
  uses-material-design: true
  assets:
    - assets/images/
