name: Branch Checker

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Fail if not from stage
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "stage" ]; then
            echo "❌ PR to main must come from stage only."
            exit 1
          fi
