name: Docker Image CI

on:
  push:
    branches: [ "main", "essence-666-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: ls && docker build back --tag java-backend:$(date +%s)

