name: Manual Docker Compose Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker-compose
        run: docker-compose up -d --build --remove-orphans
