name: Manual Deployment for STAGE

on:
  workflow_dispatch:

jobs:
  deploy:
    environment: stage
    runs-on: stage
    defaults:
      run:
        working-directory: back
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker-compose
        run: |
          echo "${{ secrets.POSTGRES_DB }}" > .env
          echo "${{ secrets.POSTGRES_USER }}" >> .env
          echo "${{ secrets.POSTGRES_PASSWORD }}" >> .env
          cat .env
          docker-compose down
          docker-compose up -d --build --remove-orphans
