name: Manual Docker Compose Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: mobile_app
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker-compose
        run: |
          sops -d .env.enc > .env
          docker-compose down
          docker-compose up -d --build --remove-orphans

