name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile_app

    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v3
        with:
          channel: 'stable'
          flutter-version: '3.25.0' 
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Analyze code
        run: flutter analyze
        
      - name: Run tests (if any)
        run: flutter test
      
      - name: Build APK (release)
        run: flutter build apk --release
